apiVersion: v1
kind: Secret
metadata:
  name: kfserving-storage-secret
  namespace: kubeflow
type: Opaque
data:
  storage-secret: <...>

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kfserving-storage-secret-sa
  namespace: kubeflow
secrets:
- name: kfserving-storage-secret
