apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "tensorflow_model_new"
spec:
  predictor:
    canaryTrafficPercent: 20
    model:
      modelFormat:
        name: nose_model_02
      storageUri: "gs://kfserving-samples/models/tensorflow/flowers-2"
