apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: outlier-detection-trigger
  namespace: kfserving-test
spec:
  broker: product-recommender
  filter:
    attributes:
      type: org.kubeflow.serving.inference.request
  subscriber:
    uri: <kfserving-test-outlier-detection-subscriber>